services:
  frontend:
    build:
      context: ./
      args:
        - VITE_BACKEND_API_URL=http://localhost:3000
    image: comsciseat_frontend
    ports:
      - "4173:4173"
    environment:
      - BACKEND_API_URL=${BACKEND_API_URL}
    networks:
      - appnet

networks:
  appnet:
    external: true
